// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDadhUEV91cIa6AfQDTRfCgmFm6x-QACzo',
    appId: '1:736273589528:web:08040cd7e77475ae01aa6d',
    messagingSenderId: '736273589528',
    projectId: 'pigdog-66a76',
    authDomain: 'pigdog-66a76.firebaseapp.com',
    storageBucket: 'pigdog-66a76.appspot.com',
    measurementId: 'G-CWN2VHKCSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuc_PfiojtCK3MydduYB6v9u-ZHevwSNk',
    appId: '1:736273589528:android:90587c7c5899600201aa6d',
    messagingSenderId: '736273589528',
    projectId: 'pigdog-66a76',
    storageBucket: 'pigdog-66a76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuY3wv1aJbuMSrtzsgkRWZHSoI9a3xGY8',
    appId: '1:736273589528:ios:7d3efa987a461e7001aa6d',
    messagingSenderId: '736273589528',
    projectId: 'pigdog-66a76',
    storageBucket: 'pigdog-66a76.appspot.com',
    androidClientId: '736273589528-f2o52sbokurao920djkd7qpa2akg3t2f.apps.googleusercontent.com',
    iosClientId: '736273589528-r6pfgrptevi7turljdnmvrp5q4kv7r8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
